image: wendo/parsec

variables:
    PARSEC_RUN_COMMAND: "./parsecmgmt2 -a build run -n 8 -i simdev"

before_script:
    - git submodule update --init

stages:
    - test

# blackscholes

test_blackscholes_gcc_pthreads_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p blackscholes -c gcc-pthreads

test_blackscholes_gcc_mth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p blackscholes -c gcc-task_mth

test_blackscholes_gcc_qth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p blackscholes -c gcc-task_qth

test_blackscholes_gcc_tbb_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p blackscholes -c gcc-task_tbb

test_blackscholes_gcc_omp_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p blackscholes -c gcc-task_omp

# raytrace

test_raytrace_gcc_pthreads_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p raytrace -c gcc-pthreads

test_raytrace_gcc_mth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p raytrace -c gcc-task_mth

test_raytrace_gcc_qth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p raytrace -c gcc-task_qth

test_raytrace_gcc_tbb_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p raytrace -c gcc-task_tbb

test_raytrace_gcc_omp_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p raytrace -c gcc-task_omp

# fluidanimate

test_fluidanimate_gcc_pthreads_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p fluidanimate -c gcc-pthreads

test_fluidanimate_gcc_mth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p fluidanimate -c gcc-task_mth

test_fluidanimate_gcc_qth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p fluidanimate -c gcc-task_qth

test_fluidanimate_gcc_tbb_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p fluidanimate -c gcc-task_tbb

test_fluidanimate_gcc_omp_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p fluidanimate -c gcc-task_omp

# dedup

test_dedup_gcc_pthreads_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p dedup -c gcc-pthreads

test_dedup_gcc_mth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p dedup -c gcc-task_mth

test_dedup_gcc_qth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p dedup -c gcc-task_qth

test_dedup_gcc_tbb_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p dedup -c gcc-task_tbb

test_dedup_gcc_omp_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p dedup -c gcc-task_omp

# streamcluster

test_streamcluster_gcc_pthreads_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p streamcluster -c gcc-pthreads

test_streamcluster_gcc_mth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p streamcluster -c gcc-task_mth

test_streamcluster_gcc_qth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p streamcluster -c gcc-task_qth

test_streamcluster_gcc_tbb_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p streamcluster -c gcc-task_tbb

test_streamcluster_gcc_omp_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p streamcluster -c gcc-task_omp


# ferret

test_ferret_gcc_pthreads_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p ferret -c gcc-pthreads

test_ferret_gcc_mth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p ferret -c gcc-task_mth

test_ferret_gcc_qth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p ferret -c gcc-task_qth

test_ferret_gcc_tbb_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p ferret -c gcc-task_tbb

test_ferret_gcc_omp_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p ferret -c gcc-task_omp

# canneal

test_canneal_gcc_pthreads_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p canneal -c gcc-pthreads

test_canneal_gcc_mth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p canneal -c gcc-task_mth

test_canneal_gcc_qth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p canneal -c gcc-task_qth

test_canneal_gcc_tbb_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p canneal -c gcc-task_tbb

test_canneal_gcc_omp_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p canneal -c gcc-task_omp	

# streamcluster

test_streamcluster_gcc_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p streamcluster -c gcc

test_streamcluster_gcc_mth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p streamcluster -c gcc-task_mth

test_streamcluster_gcc_qth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p streamcluster -c gcc-task_qth

test_streamcluster_gcc_tbb_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p streamcluster -c gcc-task_tbb

test_streamcluster_gcc_omp_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p streamcluster -c gcc-task_omp

# bodytrack

test_bodytrack_gcc_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p bodytrack -c gcc

test_bodytrack_gcc_mth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p bodytrack -c gcc-task_mth

test_bodytrack_gcc_qth_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p bodytrack -c gcc-task_qth

test_bodytrack_gcc_tbb_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p bodytrack -c gcc-task_tbb

test_bodytrack_gcc_omp_job:
    stage: test
    script:
        - cd bin
        - ${PARSEC_RUN_COMMAND} -p bodytrack -c gcc-task_omp
